export enum SetType {
  PULL_UP = 'PULL_UP',
  CHIN_UP = 'CHIN_UP',
  PUSH_UP = 'PUSH_UP',
  DIP = 'DIP',
  BARBELL_SQUAT = 'BARBELL_SQUAT',
  BARBELL_ROW = 'BARBELL_ROW',
  LAT_RAISE = 'LAT_RAISE',
  BARBELL_BENCH_PRESS = 'BARBELL_BENCH_PRESS',
  DUMBELL_INCLINE_PRESS = 'DUMBELL_INCLINE_PRESS',
}
